image: docker/compose

services:
    - docker:18.09.7-dind

before_script:
    - docker info

stages:
    - test
    - build
    - deploy

test:
    stage: test
    artifacts:
        when: always
        paths:
            - cypress/screenshots
            - cypress/videos
        expire_in: 2 days
    script:
        - docker-compose -f docker-compose-cypress.yaml build
        - docker-compose -f docker-compose-cypress.yaml up --exit-code-from cypress

build_image:
    stage: build
    only:
        refs:
            - master
            - development
    resource_group: $CI_COMMIT_REF_NAME:$CI_JOB_NAME
    before_script:
        - export API_ENDPOINT=https://api`[[ "$CI_COMMIT_REF_NAME" == "development" ]] && echo ".staging")`.menulike.com
        - echo "Building image for API_ENDPOINT=$API_ENDPOINT, tag=$CI_COMMIT_REF_NAME"
    script:
        - docker login --username $CI_REGISTRY_USERNAME --password $CI_REGISTRY_PASSWORD registry.gitlab.com
        - docker build --build-arg REACT_APP_API_URL=$API_ENDPOINT -t registry.gitlab.com/menulike/frontend/ui:$CI_COMMIT_REF_NAME . -f Dockerfile
        - docker push registry.gitlab.com/menulike/frontend/ui:$CI_COMMIT_REF_NAME

trigger_deploy:
    stage: deploy
    only:
        refs:
            - master
            - development
    resource_group: $CI_COMMIT_REF_NAME:$CI_JOB_NAME
    script:
        - apk add --no-cache curl
        - export APP_ENV=`([[ "$CI_COMMIT_REF_NAME" == "master" ]] && echo "production") || ([[ "$CI_COMMIT_REF_NAME" == "development" ]] && echo "staging")`
        - echo "Triggering build for APP_ENV=$APP_ENV"
        - curl -X POST -F "variables[APP_ENV]=$APP_ENV" -F ref=$CI_COMMIT_REF_NAME -F "variables[DEPLOY_APP]=MenulikeUi" -F token=$INFRA_DEPLOY_TOKEN -F ref=master https://gitlab.com/api/v4/projects/14781846/trigger/pipeline
