version: '3.7'
networks:
  application:
    ipam:
      driver: default
services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: https://api.staging.menulike.com
    ports:
      - '3000:3000'
    networks:
      application:
        aliases:
          - ui
  cypress:
    image: "cypress/included:4.8.0"
    entrypoint: bash
    command: ["-c", "./docker/install.sh && cypress run"]
    depends_on:
      - ui
    environment:
      - CYPRESS_baseUrl=http://ui:3000
    working_dir: /cypress
    volumes:
        - ./:/cypress
    networks:
      application:
        aliases:
          - cypress