// Control names
export const ID = 'id'
export const EMAIL = 'email'
export const PHONE_CODE = 'phone_code'
export const PHONE_NUMBER = 'phone_number'
export const COUNTRY = 'country'
export const CURRENCY = 'currency'
export const PLACE_NAME = 'name'
export const CITY = 'city'
export const ADDRESS = 'address'
export const DESCRIPTION = 'description'
export const PLACE_PIN = 'placePin'
export const SLUG = 'slug'
export const MENU_ITEMS = 'menu_items'
export const PUBLIC_ID_URL = 'public_id_url'
export const PUBLIC_URL = 'public_url'
export const QR_CODE_URL = 'qr_code_url'
// Control types
export const TYPE_TEXT = 'text'
export const TYPE_EMAIL = 'email'
export const TYPE_PHONE = 'phone'
export const TYPE_SELECT = 'select'
export const TYPE_NUM = 'tel'
// Control placeholders
export const PLACEHOLDER_EMAIL = 'Email'
export const PLACEHOLDER_PHONE_NUMBER = 'Phone'
export const PLACEHOLDER_COUNTRY = 'Country'
export const PLACEHOLDER_CURRENCY = 'Currency'
export const PLACEHOLDER_PLACE_NAME = 'Restaurant Name'
export const PLACEHOLDER_CITY = 'City'
export const PLACEHOLDER_ADDRESS = 'Address'
export const PLACEHOLDER_DESCRIPTION = 'Description'
export const PLACEHOLDER_PLACE_PIN = 'PIN code'
// Control labels
export const LABEL_EMAIL = 'Email'
export const LABEL_PLACE_NAME = 'Name'
export const LABEL_PHONE_NUMBER = 'Phone number'
export const LABEL_ADDRESS = 'Address'
export const LABEL_DESCRIPTION = 'About'
export const LABEL_COUNTRY = 'Country'
export const LABEL_CURRENCY = 'Currency'
export const LABEL_CITY = 'City'
export const LABEL_PHONE_CODE = 'Code'
