describe('Create account', function () {
  var testNumber = parseInt(Math.random() * 100000, 10)
  it('should open PIN recovery page', function () {
    cy.visit('/')
    cy.get('span').contains('Create Menu').click()
  })
  it('should fail client validation on the first page', function () {
    cy.get('input[name=email]').click()
    cy.get('div.selected-flag').click()
    cy.get('span').contains('Russia').click()
    cy.get('input[name=email]').click()
    cy.contains('Email is required')
    cy.contains('Phone is required')
  })
  it('should pass client validation for first page', function () {
    cy.get('input[name=email]').type('user@example.com')
    cy.get('div.selected-flag').click()
    cy.get('span').contains('Russia').click()
    cy.get('input[name=phone_number]').type('9269274035')
    cy.get('button').contains('Continue').click()
  })
  it('should fail client validation on the second page', function () {
    cy.get('input[name=name]').click()
    cy.get('input[name=city]').click()
    cy.get('input[name=address]').click()
    cy.get('input[name=name]').click()
    cy.contains('Restaurant Name is required')
    cy.contains('City is required')
    cy.contains('Address is required')
    cy.get('input[name=address]').type('Smal')
    cy.contains('Address should not be less than 5 characters')
    cy.get('input[name=address]').clear()
  })
  it('should pass client validation on the second page', function () {
    cy.get('input[name=name]').type('Test Resto ' + testNumber)
    cy.get('input[name=city]').type('Test City ' + testNumber)
    cy.get('input[name=address]').type('Test address' + testNumber)
    cy.get('input[name=description]').type('Test description' + testNumber)
  })
  it('fail server validation on the first page', function () {
    cy.get('span').contains('Create Restaurant').click()
    cy.contains('The email has already been taken.')
    cy.get('input[name=email]')
      .clear()
      .type('tester+' + testNumber + '@staging.menulike.com')
    cy.get('button').contains('Continue').click()
  })
  it('fail server validation on the second page', function () {
    cy.get('input[name=name]').clear().type('Menulike Restaurant')
    cy.get('span').contains('Create Restaurant').click()
    cy.contains('The name has already been taken.')
  })

  it('should succeed', function () {
    cy.get('input[name=name]')
      .clear()
      .type('Test Resto ' + testNumber)
    cy.get('span').contains('Create Restaurant').click()
    cy.contains('Menu for')
  })
})
